require: rubocop-rspec

RSpec/NestedGroups:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 90
  Exclude:
    - active_delegate.gemspec
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*.rb

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - 'to'
    - 'at'
    - 'on'
    - 'id'
    - 'in'
    - 'as'

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

AllCops:
  TargetRubyVersion: 2.5

Rails:
  Enabled: true
